name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  release:
    types: [ created ]

jobs:

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: install dependencies
        run: sudo apt-get install -y libmad0-dev
      - name: build
        run: |
          python config_unix.py
          python setup.py build
          python -m compileall -f .

  build_linux1_64:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Execute the build
        uses: docker://quay.io/pypa/manylinux1_x86_64
        with:
          entrypoint: bash
          args: /github/workspace/.github/workflows/build.sh
      - name: Archive built wheels
        uses: actions/upload-artifact@v2
        with:
          name: manylinux1_64
          path: build/*.whl
          if-no-files-found: error

  publish_linux1_64:
    if: github.event_name == 'release' && github.event.action == 'created'
    needs: [ build_linux1_64 ]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/download-artifact@v2
      id: download
      with:
        name: manylinux1_64

    - name: Publish package to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        user: __token__
        password: ${{ secrets.PYPI_API_TOKEN }}
        packages_dir: ${{ steps.download.outputs.download-path }}

  build_linux1_32:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Execute the build
        uses: docker://quay.io/pypa/manylinux1_i686
        with:
          entrypoint: linux32
          args: bash /github/workspace/.github/workflows/build.sh
      - name: Archive built wheels
        uses: actions/upload-artifact@v2
        with:
          name: manylinux1_32
          path: build/*.whl
          if-no-files-found: error

  publish_linux1_32:
    if: github.event_name == 'release' && github.event.action == 'created'
    needs: [ build_linux1_32 ]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/download-artifact@v2
      id: download
      with:
        name: manylinux1_32

    - name: Publish package to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        user: __token__
        password: ${{ secrets.PYPI_API_TOKEN }}
        packages_dir: ${{ steps.download.outputs.download-path }}

  build_linux2_24_64:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Execute the build
        uses: docker://quay.io/pypa/manylinux_2_24_x86_64
        with:
          entrypoint: bash
          args: /github/workspace/.github/workflows/build.sh
      - name: Archive built wheels
        uses: actions/upload-artifact@v2
        with:
          name: manylinux2_24_64
          path: build/*.whl
          if-no-files-found: error

  publish_linux2_24_64:
    if: github.event_name == 'release' && github.event.action == 'created'
    needs: [ build_linux2_24_64 ]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/download-artifact@v2
      id: download
      with:
        name: manylinux2_24_64

    - name: Publish package to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        user: __token__
        password: ${{ secrets.PYPI_API_TOKEN }}
        packages_dir: ${{ steps.download.outputs.download-path }}

  build_linux2_24_32:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Execute the build
        uses: docker://quay.io/pypa/manylinux_2_24_i686
        with:
          entrypoint: linux32
          args: bash /github/workspace/.github/workflows/build.sh
      - name: Archive built wheels
        uses: actions/upload-artifact@v2
        with:
          name: manylinux2_24_32
          path: build/*.whl
          if-no-files-found: error

  publish_linux2_24_32:
    if: github.event_name == 'release' && github.event.action == 'created'
    needs: [ build_linux2_24_32 ]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/download-artifact@v2
      id: download
      with:
        name: manylinux2_24_32

    - name: Publish package to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        user: __token__
        password: ${{ secrets.PYPI_API_TOKEN }}
        packages_dir: ${{ steps.download.outputs.download-path }}
